/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Katherine
 */
public class TablaVistaAvion extends javax.swing.JFrame {
     
    /**
     * Creates new form TablaVistaDocentes
     */
    public TablaVistaAvion() {
        initComponents();
        this.setLocationRelativeTo(null);
                        String bases = "";
        try{
            
            Statement sql = Conectar.getConexion().createStatement();
            String consulta = "SELECT IDAVION \n" +
", FABRICANTEAVION, TIPOAVION, CAPACIDADAVION, ESTADOAVION \n" +
"FROM AVION";
            ResultSet resultado = sql.executeQuery(consulta);
    
            int columna=5;
            
            List<String> nom= new ArrayList<>();
            
            while(resultado.next()){
                
                for(int i=0;i<columna;i++){
                 nom.add(resultado.getString(i+1));
                //nombre_array[contador][i] = resultado.getString(i+1);
                System.out.println(resultado.getString(i+1));
                }
                
            }
            Statement sql2 = Conectar2.getConexion().createStatement();
            String consulta2 = "SELECT IDAVION \n" +
", FABRICANTEAVION, TIPOAVION, CAPACIDADAVION, ESTADOAVION \n" +
"FROM AVION";
            ResultSet resultado2 = sql2.executeQuery(consulta2);
    
            
            
            while(resultado2.next()){
                
                for(int i=0;i<columna;i++){
                 nom.add(resultado2.getString(i+1));
                //nombre_array[contador][i] = resultado.getString(i+1);
                System.out.println(resultado2.getString(i+1));
                }
                
            }
            int contador=0;
            String nombre_array[][] = new String[nom.size()/columna][columna];
            for(int j=0;j<(nom.size()/columna);j++){
                for(int k=0;k<(columna);k++){
                nombre_array[j][k] =nom.get(contador);
                    contador++;
                }
            }
            resultado.close();
            sql.close();
                    Tablitita.setModel(new javax.swing.table.DefaultTableModel(
                nombre_array,
                new String[]{
                    "NUMERO DE AVION", "FABRICANTE DEL AVION"
                        , "TIPO DE AVION", "CAPACIDAD DEL AVION"
                        , "ESTADO DEL AVION"
                }
        ));
        }catch(SQLException e){
            System.out.println(e.toString());
        }
        
        ///

        
    }
                                        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tablitita = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tablitita.setBackground(new java.awt.Color(204, 204, 255));
        Tablitita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tablitita);

        jButton2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check-form_116472.png"))); // NOI18N
        jLabel1.setText("REGISTRO DE AVIONES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablitita;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
